---
title: "Reading from the Web"
author: "Chhiring Lama"
date: "2024-10-10"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r, message = FALSE, echo = FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Extracting Tables
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

Get the pieces we need:
```{r}
marj_use_df <-drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)

knitr::kable(head(marj_use_df))
```


## Learning Assessment 
Create a data frame that contains the cost of living table for New York from [this page](https://www.bestplaces.net/cost_of_living/city/new_york/new_york).

### Solution:
```{r}
url2 = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

bestplaces_nyc <- read_html(url2) |> 
  html_table( header = TRUE) |> 
  first() 

knitr::kable(bestplaces_nyc)

```

## CSS Selectors



